import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./component/layout/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{background:"linear-gradient(90deg, rgba(181,250,245,1) 0%, rgba(205,250,153,1) 51%, rgba(233,224,151,1) 100%)"}}>
      <body className={inter.className} style={{background:"linear-gradient(90deg, rgba(181,250,245,1) 0%, rgba(205,250,153,1) 51%, rgba(233,224,151,1) 100%)"}}><Navbar />{children}</body>
    </html>
  );
}
